# Generated by Django 4.1.7 on 2023-02-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skms', '0003_alter_useraccount_status_alter_useraccount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
