# Generated by Django 4.1.6 on 2023-02-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skms', '0004_comment_post_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_comments', models.TextField()),
                ('reporter_name', models.CharField(max_length=300)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('contact_preference', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=3)),
                ('report_anonymously', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=3)),
            ],
        ),
    ]
