# Generated by Django 4.1.6 on 2023-03-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skms', '0006_voice_alter_report_report_anonymously_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submitter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='submitter',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
